import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { AllocationSchema, allocationLeaf, buildMerkleTree, merkleProof, verifyMerkleProof } from "@odp/domain";
import type { Allocation } from "@odp/domain";
import { readFileSync } from "node:fs";

/**
 * Generates the fixed TS ↔ Rust cross-language Merkle test vector
 * (P0-4 §6) using REAL Solana pubkeys from the demo key registry.
 *
 * Outputs:
 *   programs/merkle-vector/vector.json    — human-readable vector
 *   programs/merkle-vector/src/vector_data.rs — generated Rust literals
 *
 * The Rust checker recomputes everything from scratch (zero deps) and must
 * produce IDENTICAL leaf hashes / root / proofs. Only then does
 * MERKLE-WIRE-FORMAT graduate PROVISIONAL → FROZEN-V1.
 */
export const VECTOR_DISTRIBUTION_ID = "dst_aurora_demo_001";

const ownDir = path.dirname(fileURLToPath(import.meta.url));
const keys = JSON.parse(
  readFileSync(path.join(ownDir, "../fixtures/keys/devnet-pubkeys.json"), "utf8"),
) as Record<string, string>;

function alloc(wallet: string, amount: string): Allocation {
  return AllocationSchema.parse({
    distribution_id: VECTOR_DISTRIBUTION_ID,
    human_id: wallet,
    wallet,
    amount,
  });
}

const allocations = [alloc(keys.maya!, "5000"), alloc(keys.dan!, "5000")];
const leaves = allocations.map(allocationLeaf);
const tree = buildMerkleTree(leaves);
const root = tree.root.toString("hex");

interface VectorEntry {
  wallet: string;
  amount: string;
  leaf_preimage_utf8: string;
  leaf_hash_hex: string;
  proof_hex: string[];
}

const entries: VectorEntry[] = allocations.map((a, i) => {
  const preimage = `${a.distribution_id}\n${a.wallet}\n${a.amount}`;
  return {
    wallet: a.wallet,
    amount: a.amount,
    leaf_preimage_utf8: preimage,
    leaf_hash_hex: leaves[i]!.toString("hex"),
    proof_hex: merkleProof(tree, leaves[i]!).map((p) => p.toString("hex")),
  };
});

// Negative cases: must all verify FALSE against the same root.
const negatives = [
  {
    case: "wrong_wallet",
    distribution_id: VECTOR_DISTRIBUTION_ID,
    wallet: keys.sib!,
    amount: "5000",
  },
  {
    case: "wrong_amount",
    distribution_id: VECTOR_DISTRIBUTION_ID,
    wallet: keys.maya!,
    amount: "4999",
  },
  {
    case: "cross_distribution",
    distribution_id: "dst_other_999",
    wallet: keys.maya!,
    amount: "5000",
  },
].map((n) => {
  const leaf = allocationLeaf(n);
  const proof = merkleProof(tree, leaves[0]!); // attacker replays maya's proof
  return { ...n, expected_leaf_hash_hex: leaf.toString("hex"), verify: verifyMerkleProof(leaf, proof, tree.root) };
});

const vector = {
  algorithm: "sha256; leaf = sha256(utf8(dist_id + '\\n' + wallet + '\\n' + amount)); leaves sorted; sibling-sorted pairing; odd promoted",
  distribution_id: VECTOR_DISTRIBUTION_ID,
  root_hex: root,
  entries,
  negatives,
  positive_verify: entries.map((_, i) => verifyMerkleProof(leaves[i]!, merkleProof(tree, leaves[i]!), tree.root)),
};

const outDir = path.resolve(ownDir, "../../../programs/merkle-vector");
writeFileSync(path.join(outDir, "vector.json"), JSON.stringify(vector, null, 2) + "\n", "utf8");

// Generate the Rust data file (hex literals — no JSON parsing, no deps).
const rs = `//! GENERATED by packages/distribution-engine/scripts/gen-merkle-vector.ts — do not edit.
//! Cross-language test vector (TS ↔ Rust) for the ODP merkle wire format.

pub const DISTRIBUTION_ID: &str = "${VECTOR_DISTRIBUTION_ID}";
pub const ROOT_HEX: &str = "${root}";

pub struct Entry {
    pub wallet: &'static str,
    pub amount: &'static str,
    pub leaf_preimage: &'static str,
    pub leaf_hash_hex: &'static str,
    pub proof_hex: &'static [&'static str],
}

pub const ENTRIES: &[Entry] = &[
${entries
  .map(
    (e) =>
      `    Entry { wallet: "${e.wallet}", amount: "${e.amount}", leaf_preimage: ${JSON.stringify(e.leaf_preimage_utf8)}, leaf_hash_hex: "${e.leaf_hash_hex}", proof_hex: &[${e.proof_hex
        .map((p) => `"${p}"`)
        .join(", ")}] },`,
  )
  .join("\n")}
];

pub struct Negative {
    pub case_name: &'static str,
    pub distribution_id: &'static str,
    pub wallet: &'static str,
    pub amount: &'static str,
    pub expected_leaf_hash_hex: &'static str,
}

pub const NEGATIVES: &[Negative] = &[
${negatives
  .map(
    (n) =>
      `    Negative { case_name: "${n.case}", distribution_id: "${n.distribution_id}", wallet: "${n.wallet}", amount: "${n.amount}", expected_leaf_hash_hex: "${n.expected_leaf_hash_hex}" },`,
  )
  .join("\n")}
];
`;
writeFileSync(path.join(outDir, "src/vector_data.rs"), rs, "utf8");

console.log(`root: ${root}`);
console.log(`entries: ${entries.length}, negatives: ${negatives.length}`);
console.log(`positive_verify: ${vector.positive_verify}`);
console.log(`negative verify results: ${negatives.map((n) => `${n.case}=${n.verify}`).join(", ")}`);
console.log(`written: ${outDir}/vector.json + src/vector_data.rs`);
